### ISSUE TITLE
Emscripten example

### ISSUE THREAD

**Issue by gfwilliams** [jcubic/jquery.terminal#150]
It now looks pretty easy to compile C code into JavaScript so it can run in the browser with Emscripten (I just did it with one of my projects)... However the standard HTML output with `emcc ... -o myfile.html` produces a prompt window every time input is required.

It'd be awesome if you could provide an example on your site of replacing this prompt (and the output window) with jquery.terminal...

Seems like I can't attach the files, but I've put some example code online so you can see what Emscripten currently does by default: http://www.pur3.co.uk/tmp/loopback/loopback.html

**Comment by jcubic** [comment]
There was new StackOverflow question and I was able to create a hack that allow to use async read terminal method instead of browser build in prompt, the code abuse fetch emscripten API to do this.

[How can I run an interactive program compiled with Emscripten in a web page?](https://stackoverflow.com/q/48292269/387194)

I'm provided SO instead of solution gist, so you see how OP input C code look like. The question have open bounty so maybe someone will come up with better solution.
