### ISSUE TITLE
Add support for terminal cursor movement with Ansi/VT100 codes

### ISSUE THREAD

**Issue by gpetrov** [jcubic/jquery.terminal#196]
It will be really usefull if we can also do some cursor movements with the Ansi codes, described in:

http://www.termsys.demon.co.uk/vtansi.htm

This way we can do cool terminal animations, text progressbars etc.

Very cool in combination of node modules like Charm.

https://github.com/substack/node-charm

Please consider implementing this.

Thanks!

**Comment by jcubic** [comment]
I don't think it will be possible to add cursor movement from the server. Adding cursor up/down will be impossible because underneath terminal use cmd plugin that sit below the output and you can't move it around.

But even that you can still add animation by setting command line, check [user typing animation](http://terminal.jcubic.pl/examples.php#user-typing), there is better to do this type of animation on the client then on the server, besides terminal is command based so you can't modify single command from the server, it execute your function on enter.
