### ISSUE TITLE
On Android, first character can't be deleted

### ISSUE THREAD

**Issue by remram44** [jcubic/jquery.terminal#235]
I enter `ls`, press enter, on the next line `ls` is already entered. If I backspace to remove it, the `l` will still show, though the next character I enter will take its place. Basically there is always one character displayed (and the caret shows after it), and new input lines are initially filled with the previous line I entered.

**Comment by jcubic** [comment]
I'm unable to reproduce, what browser and version of android you're using?

**Comment by remram44** [comment]
I'm using Chrome 49.0.2623.105 on Android 6.0.1 (cyanogenMod 13 on Nexus 5).

Also the left and right keys don't move the caret (it stays at the end of the input line).

**Comment by jcubic** [comment]
Unfortunately I don't have this device so I can test it. I have only old 2.3.3 with build in webkit browser and it work there, but the keyboard don't have arrows so I didn't work on it.

**Comment by x-mugen-x** [comment]
Works fine on CM 13 (6.0.1) Nexus 5 stock browser and firefox (confirmed) must be a chrome issue.

**Comment by jpatrickpark** [comment]
I experienced similar issue, but while typing Korean letters on ChromeOS 53.0.2785.103 (64-bit).

I can type Korean words and press enter to transmit data to jQuery object, and then it will display new prompt without any user input written on it, but when I type some more Korean on the new prompt the data from previous prompt reappears. Same thing happens when I try to delete those Korean words by pressing backspace or Ctrl+u, all the previously written Korean words reappear when I type some more Korean.

Curiously, this problem does not occur on my Android device.

**Comment by jcubic** [comment]
Can somebody test if #86 fixed this issue as well? @jpatrickpark Korean should work because that issue is for input method.

**Comment by jcubic** [comment]
It seems it's resolved.
