### ISSUE TITLE
Don't write command after type

### ISSUE THREAD

**Issue by BL4CKC1PH3R** [jcubic/jquery.terminal#250]
I have an issue, i want to execute a command ex: `msg <user> <msg>`, 
but i dont want to show the command in the terminal, how i can ommit ?

Thanks, anyway, if anybody want, i can print the screen!

**Comment by jcubic** [comment]
You can use exec with true as second argument (which indicate that command should be executed silently) like:
```javascript
term.exec("msg <user> <msg>", true);
```

**Comment by jcubic** [comment]
If you mean that you want to not have echo command when you type command it's not possible. Naive approch to make it work would be to allow return false from user command and then not echo the command but echo command need to be executed first because user interpreter may echo something and it will echo command after user echo so this is not possible. I can add option to prevent echo command for all commands, you will be able to use keypress event to get command using `term.get_command()` and if command match /^\s*msg\s*/ you will be able to turn off echoCommand.

**Comment by jcubic** [comment]
From 0.11.3 version you can use this code:

```javascript
$('...').terminal(function(command, term) {
}, {
    keydown: function(e, term) {
         if (term.get_command().match(/^\s*msg\s*/)) {
             term.option('echoCommand', false);
         } else {
             term.option('echoCommand', true);
         }
    }
}
```

or you can shorten that code using:

```javascript
term.option('echoCommand', !term.get_command().match(/^\s*msg\s*/));
```
