### ISSUE TITLE
Custom serialisation doesn't sanitise illegal unicode characters

### ISSUE THREAD

**Issue by benelliott** [jcubic/jquery.terminal#266]
Hi,

Thanks for the library.

Could you explain the motive for including a `json_stringify` method rather than just using the native `JSON.stringify`?

The custom method doesn't seem to sanitise illegal characters in strings properly. This can cause the terminal to error if a user inputs illegal characters as a command, which is then loaded from local storage the next time the page is loaded. The `JSON.parse` fails on the illegal characters and stops the terminal from initialising.

An easy way to test this is to open an image file in a text editor, copy and paste the contents into the terminal and execute the command, then refresh the page to see the terminal load the command history.

I made a quick fork of the library in which I just rely on JSON.stringify and the problem disappears.

**Comment by jcubic** [comment]
I've created my own json stringify because I was using [Biwascheme](http://www.biwascheme.org/) (one of the examples use it) that use protoytype.js that did something with arrays that that make invalid JSON, but in the meantime biwascheme replaced prototype with jQuery. I can change json_stringify with JSON.stringify but I will need to update biwacheme example.

**Comment by jcubic** [comment]
replaced json_stringify with JSON.stringify in version 0.11.15

**Comment by benelliott** [comment]
Thanks :)
