### ISSUE TITLE
ctrl-d issues

### ISSUE THREAD

**Issue by philip-ulrich** [jcubic/jquery.terminal#300]
### Expected behavior
ctrl-d should exit out of a paused terminal

### Actual behavior
ctrl-d does nothing. if you implement your own ctrl-d, then it works ... but you have to change tabs and then refocus for it to work. 

### Steps to reproduce
use command 'help' in example, will pause terminal.. try to ctrl-d out

custom ctrl-d: http://codepen.io/anon/pen/QpQBXO
built-in ctrl-d: http://codepen.io/anon/pen/vxdzNG

Granted, I could be misunderstanding how this should work... but it does not look to be working properly based on my understanding.

**Comment by jcubic** [comment]
I've added CTRL+D for canceling AJAX requests and resume interpreter, if there are any pending requests.

I can add option to resume the interpreter when paused. Should it also exit or should it just resume() and then you will need to press CTRL+D again to exit? I think that the latter is better because you can pause when you type something and it should not exit but delete one character forward and I think it should not delete that character if there is no prompt, so it would be better to just resume.

**Comment by philip-ulrich** [comment]
Ah, when you said resume in the API reference, I just assumed that meant resuming from pause.

I think it would be a good option to have. I can think of lots of terminal-ish situations when a full screen display would be fitting (using pause) and being able to ctrl-d out of it would make sense. I also agree that the latter is better. You don't necessarily need to exit if you are in a pause. 

In regard to the custom ctrl-d, did you also notice the "switch to another tab" issue I was seeing? Does this have to do with the way your implementation of ctrl-d was interacting with mine? Or maybe how pause is interacting with it? Prior to pausing.. I can ctrl-d without issue as much as I want. Once I pause, I have to change browser tabs to be able to use it again.

**Comment by jcubic** [comment]
Your code was working only when you refocus because focus was enabled command line even that it was hidden. You could type something and when you press CTRL+D the text would appear.

The fix is in master branch, your both demos should now work (remember to clear the cache). But no need for custom CTRL+D anymore.
