### ISSUE TITLE
Autocompleting ambiguous commands containing spaces adds a backslash at the end of the completed word

### ISSUE THREAD

**Issue by QuentinBarrand** [jcubic/jquery.terminal#306]
In this test case, we provide two ambiguous commands that contain spaces to `completion`:
`example one` and `example two`.

### Expected behavior
After writing `exa` and pressing TAB, the autocompletion engine writes `example ` (with a trailing space) and prints `example one` and `example two` under the current line.

### Actual behavior
The autocompletion engine writes `example\ ` and prints `example\ one` and `example\ two` under the current line.
This codepen illustrates the issue: https://codepen.io/anon/pen/zwEoWG

### Steps to reproduce
Pass the following array to `complete`: `['example one', 'example two']`

**Comment by jcubic** [comment]
This is a feature, because if it complete as "example " then when you type "o" and press tab again it will not complete the text because it will try to complete word "o" and not "example o".

When you parse command it will replace `"\ "` with `" "`. I can add option to not enter \ to spaces but then the case when you type "example o" will not complete text.

Maybe I can change the logic to get the complete word and match ending of the whole text with regex. Will test.

**Comment by jcubic** [comment]
I was trying to implement completion using arbitrary text but I've failed and I think it's not possible. you need to have spaces as boundary or beginning of the string if you use wordAutocomplete option to false (I've just notice that it will not work, need to fix it)

I can add option to disable escaping, (maybe `bashEscape` that's set to true by default) and then if you use `wordAutocomplete: false, bashEscape: false` you will have whole line completion with no escaping.

**Comment by jcubic** [comment]
I've added an option completionEscape and fixed wordAutocomplete, so you can now do (in devel branch, will be in next 1.4.0):
```
$('#id').terminal($.noop, {
   completion: ['example one', 'example two']
   completionEscape: false,
   wordAutocomplete: false
});
```
