### ISSUE TITLE
option 'flush: false' does not work

### ISSUE THREAD

**Issue by carolkey** [jcubic/jquery.terminal#310]
```
$('body').terminal(function(command, term){
    term.echo('some text', {raw: true, flush: false});
});
```
It always show the text, I think 'flush' not work.
note: I have never call the 'flush()' method.

**Comment by jcubic** [comment]
I can't reproduce, which version of jQuery Terminal you're using?

**Comment by jcubic** [comment]
If you run this code twice it will echo both texts because terminal is echo command and it need to call flush, and flush is flushing previous texts.

If you want to have flush that don't echo anything you can use echCommand option set to false:

```javascript
var term = $('body').terminal(function(command) {
    if (command.match(/flush/)) {
        this.flush();
    } else {
        this.echo(this.get_prompt() + command, {flush: false});
        this.echo('some text', {
            raw: true,
            flush: false
        });
    }
}, {
    onBlur: function() {
        return false;
    },
    echoCommand: false
});
```

[Here is demo](http://codepen.io/jcubic/pen/KmErMo?editors=1010)

**Comment by carolkey** [comment]
Thanks for your demo
