### ISSUE TITLE
it can only input letter,can not input japanse or chinese

### ISSUE THREAD

**Issue by hnujxm** [jcubic/jquery.terminal#323]
### Expected behavior
can  input japanse or chinese
### Actual behavior
can only input letter

**Comment by jcubic** [comment]
Can you tell what browser/os you're using and how you have your keyboard configured?

**Comment by jcubic** [comment]
Right now I can only test Japanese (Kana) keyboard layout on Xubuntu and entering Japanese letters work with this layout but I didn't test input method, if you have other OS then this issue will need to wait until my new laptop get fixes so I can run VirtualBox without problems.

The click to get cursor change don't work because Japanese characters are wider then normal monospace font characters, this one I can fix right now.

**Comment by jcubic** [comment]
Fixed click on wider characters in devel branch.

**Comment by hnujxm** [comment]
sorry。I running the application on windows10 width chrome 59.0.3071.115，the keyboard is sougou，a chinese keyboard。the keyboard can be download  at https://pinyin.sogou.com/

**Comment by jcubic** [comment]
I've fixed the issue of entering text (in devel branch) but click to move cursor and also long line wrapping when text have wider character is not working yet. Will fix that later and push version 1.5.1.

**Comment by jcubic** [comment]
Fixed final part moving cursor and long line wrapping also work but for all Japanese or Chinese characters it don't occupy whole terminal width.

**Comment by jcubic** [comment]
The fix is in master
