### ISSUE TITLE
onTerminalChange with many terminals on screen

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#356]
### Expected behavior
call  onTerminalChange 1 time.

### Actual behavior
for example : i have 16 terminals on screen. when i click on terminal, function onTerminalChange fired 16 times instead of 1

**Comment by jcubic** [comment]
It need to be called 16 times if every terminal have the option set, one for each terminal. If you want it to be execute once you need to define it only in one terminal.

In last commit I've changed to context to be terminal that for which it came from and argument is terminal that is selected, so you can defined callback as this:
```
                 onTerminalChange: function(selected_terminal) {
                     console.log('change from ' + this.id() + ' selected terminal ' +
                                 selected_terminal.id());
                 },
```

**Comment by jcubic** [comment]
so if you want it execute once, if the function is the same for all terminals, you can use this:
```javascript
                 onTerminalChange: function(selected_terminal) {
                     if (this.id() == selected_terminal.id()) {
                          console.log('terminal change to ' + this.id());
                     }
                 }
```

**Comment by jcubic** [comment]
it probably should execute 2 times, one for terminal that you exit and one that you enter. Did you defined that event only on one terminal? will check it tomorrow. 13.11.2017 11:01 AM artursOs <notifications@github.com> napisał(a):Expected behavior
call  onTerminalChange 1 time.
Actual behavior
for example : i have 16 terminals on screen. when i click on terminal, function onTerminalChange fired 16 times instead of 1
Steps to reproduce
Browser and OS
