### ISSUE TITLE
You can't type characters on android

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#39]
When you enter a site with fullscreen terminal on android the keyboard is popup but you can't enter characters

Fixing this bug will probably fix issue on iPhone and iPad.

**Comment by KeithTurkowski** [comment]
I did some more testing, in Chrome on Android 4.4.4

The key_down(e) function is triggered  when you press a key, e.which and e.keyCode will give the correct value for the key pressed. However, the character is not displayed in the terminal prompt. I will do some more testing, but I believe to fix this, android must be detected and the character injected to the command prompt.

**Comment by KeithTurkowski** [comment]
Summary: key events across Android browsers are inconsistent, implemented incorrectly, and buggy.

Links related to what is causing this issue:
http://www.w3.org/TR/DOM-Level-3-Events/#events-inputevents
https://developer.mozilla.org/en-US/docs/Web/Events/compositionstart
http://techblog.open-xchange.com/2014/12/02/android-chrome-and-composition-events/
https://code.google.com/p/chromium/issues/detail?id=118639
https://code.google.com/p/chromium/issues/detail?id=422685
https://github.com/RobinHerbots/jquery.inputmask/issues/465

I "fixed" this issue on the latest version of Chrome for Android by caching e.which in the key_down function, and then adding a listener for the compositionupdate event.


`-        $(document.documentElement || window).bind('keypress.cmd', function(e) {
+        var keystrokes = function(e) {
-        }).bind('keydown.cmd', keydown_event);
+        $(document.documentElement || window).bind('keypress.cmd', keystrokes).bind('keydown.cmd', keydown_event);


+        $(document.documentElement || window).bind('compositionupdate', function(e){if(!lastkey.bad) keystrokes(lastkey);});

+        lastkey = {which: e.which + (e.shiftKey ? 0 : 32), ctrlKey: e.ctrlKey, bad: e.which == 0};`

The 'keypress' event will send the character that is pressed, while the 'keydown' event only sends the key pressed, so you have to check to see if shift is pressed in order to determine upper/lower case, etc.

This is because the keypress event does not trigger on Android Chrome when a composition is being done, although it will trigger on non-compositions, like pressing '1' or 'ENTER'.

Also, there is apparently a bug, in that when a composition completes (by pressing enter for example) when the next composition starts and the next keydown event will send the value of 0 for e.which (but will still trigger all the events).

This is all great, except that this code does not work on the built in "Internet" browser app that comes with Android 4.4.4 or with Firefox on Android.

All 3 browsers seem to handle compositions differently, and send different events in different orders, so here's what happens when the following sequence of keys is pressed.

Sequence: abc<ENTER>abc<ENTER>

(kd) = keydown event
(kp) = keypress event
(ku) = keyup event
(cs) = compositionstart event
(cu) = compositionupdate event
(ce) = compositionend event
(i) = input event
(bi) = beforeinput event

Windows Firefox:
> (kd)(kp)a(ku)(kd)(kp)b(ku)(kd)(kp)c(ku)(kd)
> (ku)(kd)(kp)a(ku)(kd)(kp)b(ku)(kd)(kp)c(ku)(kd)
> (ku)

Android Chrome:
> (kd)(cs)(cu)(i)(ku)(kd)(cs)(cu)(i)(ku)(kd)(cs)(cu)(i)(ku)(kd)(ce)(i)(ku)(kd)
> (ku)(kd)(cs)(cu)(i)(ku)(kd)(cs)(cu)(i)(ku)(kd)(cs)(cu)(i)(ku)(kd)(ce)(i)(ku)(kd)
> (ku)

Android Firefox
> (cs)(cu)(i)(cu)(i)(i)(cu)(i)(i)(cu)(i)(i)(ce)(i)(kd)(kp)A(ku)(kd)(kp)b(ku)(kd)(kp)c(ku)(kd)
> (ku)(cs)(cu)(i)(cu)(i)(i)(cu)(i)(i)(ce)(i)(kd)(kp)A(ku)(kd)(kp)b(ku)(kd)(kp)c(ku)(kd)(kp)a(ku)(kd)(kp)b(ku)(kd)(kp)c(ku)(kd)
> (ku)

Android Internet (default browser)
> (kd)(cs)(cu)(i)(ku)(kd)(cs)(cu)(i)(ku)(kd)(cs)(cu)(i)(ku)(ce)(i)(kd)(ku)(i)(kd)
> (ku)(kd)(cs)(cu)(i)(ku)(kd)(cs)(cu)(i)(ku)(kd)(cs)(cu)(i)(ku)(ce)(i)(kd)(ku)(i)(kd)
> (ku)

Android Internet (default browser) seems to be based on an older version of Chrome, it's very similar except for a minor different in events when a compositionend happens. However, after the first composition it will start sending garbage keys.

Android Firefox seems to do something different (and better) than Chrome, since it actually does a composition and when the compositionend occurs it triggers the (keypress) events from the composition in sequence, this would make Firefox work nicely without any changes necessary, except that it will sometimes store all the keys pressed for the session and injects them into a composition. So you will get every command character you typed flooding into the terminal.

The composition events seem to have no information on the keys being pressed, or inconsistent data between the browsers, so you can only get the key from e.which in keydown events semi-reliably.

Perhaps there is some clever way to do this differently by binding an 'input' event handler, but I don't really see how to make a generic solution that works on all Android browsers due to buggy inconsistent implementation, especially with Chrome.

I gave up on solving the problem in this way, and solved the problem using an <input> field instead, which I will detail in the following post.

**Comment by KeithTurkowski** [comment]
Here's my solution to the problem: https://github.com/KeithTurkowski/jquery.terminal/commit/23132445aef8496aa2c35b5e3f95ef872282c6ef#diff-dba734ca44649c50a5de68bf61511841

I use an <input> field to capture the input instead of capturing keypress, it probably isn't fully functional for all the features of jquery.terminal, but it does solve the problem for my purposes.

Unfortunately, the way these events are handled on different browsers on Android is so terrible, I don't think a key event solution is really feasible.

**Comment by KeithTurkowski** [comment]
Also, if you want to incorporate this code, I think the following line of code is poorly placed:

+ self.find('.altinput').focus();

I hacked it in without fully understanding the purpose of the code around it.

**Comment by tasl33m** [comment]
Thanks for this, Keith. I have been experiencing the exact same problem, thanks perhaps to your solution the "Internet" and "Chrome" apps work fine for me on Android. My current issue surrounds the "Google Keyboard" app. The only keystrokes that register are numerals, despite using your updated solution. Any ideas?

**Comment by KeithTurkowski** [comment]
When you create your terminal, are you using "altinput: true" in the settings? It should work since it's using an <input> element.

**Comment by tasl33m** [comment]
Hi Keith. Good point. I've added that in (not sure if in the right place?). Could you take a look for me here if you have a spare couple minutes ... can anyone see what I've done wrong? Hope it is an obvious fix. http://chaostheorem.com/android

**Comment by jcubic** [comment]
You need to pass it as option to second argument.

**Comment by tasl33m** [comment]
Oh my! THANK YOU

**Comment by tasl33m** [comment]
Okay back to a couple problems. I was hoping that Keith's script would work on both mobile devices as well as Desktops. It does, to an extent. I'm finding that the new script doesn't work on some devices. Eg: IE8 (yes, I know it's 6 years old :P)... Does anyone have a compatibility chart? My friend has an iPhone 5 with a slightly older iOS version and he is not able to hit the return/enter key in Safari, leaving the terminal useless. Any feedback would be terrific. Thanks!

**Comment by tasl33m** [comment]
Does anyone else have this same problem? http://chaostheorem.com/android is not compatible with IE11. The enter/return key on the keyboard isn't recognised. Instead, a mouse click event is required? No way to have the script work for both mobiles and desktops?

**Comment by KeithTurkowski** [comment]
I do something like:

  altinput: is_android()

Find a library that detects android / mobile.

**Comment by tasl33m** [comment]
Didn't think of that. Thanks. For anyone else stuck, use this:

var ua = navigator.userAgent.toLowerCase();
var isAndroid = ua.indexOf("android") > -1; //&& ua.indexOf("mobile");

altinput: isandroid //second argument

**Comment by gpetrov** [comment]
Was there a solution to this issue?

I'm using an older embedded chrome browser and cannot type anything in jquery terminal.

when running:  http://terminal.jcubic.pl/test.php

i get:

keydown
keyup
no keypress

I see in my user agent string AppleWebKit/533.19.4 = so it is pretty old but unfortunately I'm stuck with it and I really want to use the jQuery Terminal in there as well!

a solution will be greatly appreciated.

**Comment by jcubic** [comment]
Right now you can try to use [KeithTurkowski fork](https://github.com/KeithTurkowski/jquery.terminal). You will need to use option `altinput: true`

**Comment by gpetrov** [comment]
works indeed! thanks!!

Any chance to implement this on the main branch as well?

**Comment by jcubic** [comment]
Yes I will implement this in main branch, I want it for 0.9.0 version.

**Comment by jcubic** [comment]
Finally added Keith Turkowski solution with input event, I didn't add change event though.

**Comment by lshaf** [comment]
still not fix on mine.
I'm using android 6.0.1 with chrome v 54.0.2840.68 and with default keyboard.
somehow it's work but my text doesn't appear on terminal screen with fullscreen mode.

you can try it out here https://biol.be/qrpoc

**Comment by jcubic** [comment]
I can't open that link on my android phone (2.3.3 with default browser), I've got error that the browser can't establish secure connection but it work on my laptop.

**Comment by lshaf** [comment]
@jcubic waw, you have old phone 😃 .
maybe that's your mobile phone connection problem?
It's just weird, your laptop can access it but android phone can't?

**Comment by lshaf** [comment]
ohh and I remember 1 more thing.
I've visit your site http://terminal.jcubic.pl/ using my phone and however, when I tap on demo terminal, it throw me to comment terminal. it just keep focused on comment section.

**Comment by jcubic** [comment]
try to disable terminal on init using `enabled: false`

**Comment by jcubic** [comment]
I've copied your code to my server and testing, don't know yet why your code is not working it work here: http://terminal.jcubic.pl/android.html

**Comment by jcubic** [comment]
Fixed in version 0.11.12

**Comment by lshaf** [comment]
big thanks, it works 😸 .

**Comment by jcubic** [comment]
I think this issue can be closed then.
