### ISSUE TITLE
Paste using context menu/right click?

### ISSUE THREAD

**Issue by U-Design** [jcubic/jquery.terminal#450]
Is pasting content using right click possible? 
Wanted to imitate the behavior where the copied item is just pasted using a right click.

**Comment by jcubic** [comment]
It should work

**Comment by U-Design** [comment]
So does that mean there is an implementation in jquery.terminal already for it. 
The expectation is that after copying some line I should be able to directly paste using ri8 click onto the jquery.terminal. 
Currently, to achieve this is there an option or some hack is required?
Anyways could not get the relation to Codemirror here.

**Comment by jcubic** [comment]
It works in VirtualBox win10 Chrome but you can't have text selection on terminal, maybe I can do something about it.

**Comment by jcubic** [comment]
Can you record short video of the problem? but only if you don't have anything selected. I think you you can fix it because if you have selection you have copy option and without you can have paste.

**Comment by jcubic** [comment]
Hm, codemirror that both in same time. Maybe I can do the same.

**Comment by jcubic** [comment]
I think it will be imposible to have both copy and paste when you right click on selection because I would need to add selection to cmd textarea and that is only for command line. As I said Codemirror is different. His textarea have the same text as selection so his copy can be processed on textarea.
