### ISSUE TITLE
First close bracket moved to end when has ansi colors

### ISSUE THREAD

**Issue by fernandoval** [jcubic/jquery.terminal#476]
### Expected behavior
My App v1.0.0
Usage: command argument [option] [parameter]

### Actual behavior
My App v1.0.0
Usage: command argument [option [parameter]]

### Steps to reproduce
term.echo('My App [32m1.0.0[39m\nUsage: command argument [option] [parameter]');

### Browser and OS
Chrome 73.0.3683.75 - Ubuntu 18.04.2 LTS

https://codepen.io/fval/pen/aMRPwK

**Comment by jcubic** [comment]
The problem is that unix formatting don't know how to handle brackets. The output is correct but by default you can mix both ansi escapes and unix formatting so you need to escape formatting.

```javascript
$.terminal.from_ansi('My App �[32m1.0.0�[39m\nUsage: command <argument> [<option>] [<parameter>]')
"My App [[;#008400;]1.0.0][[;inherit;]\nUsage: command <argument> [<option>] [<parameter>]]"
```
so first closing bracket is not disappearing but it close `[39m` formatting prematurely, so everything that after is outside of formatting even real closing formatting that at the end. This is correct behavior. It would be really hard to figure out what user want if he want brackets or mix formatting with ansi escapes so there is option, `unixFormattingEscapeBrackets` added by [Marcel Link](https://github.com/ml1nk) in PR.

```
var term = $('body').terminal(function(command, term) {
    term.echo('My App [32m1.0.0[39m\nUsage: command <argument> [<option>] [<parameter>]');
}, {
    unixFormattingEscapeBrackets: true
});
```

this is global option but I can make it work in echo if needed.

**Comment by fernandoval** [comment]
Sorry I didn't see this option in documentation.

Works great for me.
