### ISSUE TITLE
Cursor won't move when a long text is pasted

### ISSUE THREAD

**Issue by wavifu** [jcubic/jquery.terminal#480]
### I have question related to jQuery Terminal

I am pasting a long text to the demo, and when I use left and right arrow to move around, it's unmovable, and the page is hang. Do you have any suggestions to make it work with long text?

**Comment by jcubic** [comment]
Do you have link to that demo?

**Comment by jcubic** [comment]
You mean demo on the website? What text did you've pasted?

**Comment by wavifu** [comment]
Yes. It's a lorem text:

> Phasellus augue lectus, accumsan pellentesque ultrices sit amet, eleifend vitae tellus. Phasellus cursus elit nec lorem rutrum condimentum. Ut auctor nulla id facilisis vehicula. Cras laoreet velit vitae convallis eleifend. Suspendisse potenti. Morbi maximus sapien id risus sodales dapibus. Suspendisse vulputate hendrerit ex, a vulputate augue vulputate et. Donec sit amet finibus eros, ut eleifend ligula. Quisque tincidunt, neque eget porta tempor, nibh leo suscipit diam, in scelerisque arcu sapien non sem. Pellentesque faucibus velit ut nunc imperdiet lobortis. Suspendisse bibendum nunc eget laoreet fermentum. Ut purus tortor, varius ut ipsum id, convallis dapibus ligula. Sed ac dui commodo est ultrices vulputate. Integer in luctus quam, vitae rutrum elit. Phasellus fermentum quam id justo ultricies, ac pulvinar nisl blandit. Maecenas non venenatis sapien, sit amet blandit ex.

**Comment by jcubic** [comment]
For me it's just slow, it unhang after a while (couple of miliseconds). The problem is that on each cursor change the whole command line is re-rendered. I need to figure out how to not render whole command. Maybe update only single line were cursor is located.

This can be improved. Thanks for this report.

**Comment by jcubic** [comment]
I've made some improvements, there is still issue with render, reflow happen 2 times one because of `getPropertyValue` in function `fix_cursor` related to cursor animation. Maybe I will be able to remove that function and put responsibility to the user, to call some function after change of `--animataion` css prop. Or add api to change cursor animation in JS (that will update `--animation` css prop).

**Comment by jcubic** [comment]
You can check devel branch. I works much better now.

**Comment by wavifu** [comment]
Thanks. It works great!
