### ISSUE TITLE
Backspace is Slow

### ISSUE THREAD

**Issue by thagh05t** [jcubic/jquery.terminal#532]
### I have question related to jQuery Terminal

Is there a way to speed up the rate at which backspace key deletes characters on repeat? Such as when the left and right arrows are pressed...

**Comment by jcubic** [comment]
It suppose to be changed with `repeatTimeoutKeys: []` that should be default. When adding mobileDelete option it should disable default HOLD+BACKSPACE delay. (the code that check if key is on that option array list don't work).

So default should not to delay backspace, since it don't do word delete by default on desktop.

**Comment by jcubic** [comment]
option: `repeatTimeoutKeys` is now empty array, and adding HOLD+BACKSPACE don't have any effect because delay for that combo is controlled by `mobileDelete` option.
