### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by 4s3ti** [jcubic/jquery.terminal#561]
### I have question related to jQuery Terminal

Hi, 

I am not sure if this the correct place to place this, but i have been reading the documentation, asked around on IRC, tried the chat on the website however couldn't get any answer.

according to the documentation [Here](https://terminal.jcubic.pl/examples.php#mobile) it should work on mobile out of the box, but seems it is not to be happening, as i am not really a web developer i can't really understand why therefore i am asking fore some help here. 

My website generates html code with python and jinja2, and has the most recent jquery and jquery.terminal

All the code is opensource here https://github.com/4s3ti/terminalCV
and you can see it working here: https://cv.4s3ti.net

Any hints and help would be appreciated, 
Thanks in advance.

**Comment by jcubic** [comment]
The problem is:
```
        onBlur: function() {
            return false;
        }
```

Remove it, it was old solution to fill screen issue, right now there are better ones with just CSS. It prevent keyboard to open because on mobile the terminal can't be enabled by default and this will disable this. When you remove this, you will have disable terminal on init, and you will need to tap to enable virtual keyboard (that's requirement by mobile platform that keyboard can't be open on initialization).

There is even issue to document this properly everywere, so people will find it #555

**Comment by 4s3ti** [comment]
Thanks a log @jcubic That made the trick!! 

As I said this is kinda out of my area of comfort so was kinda confused what could that be. 

Thanks a lot for amazing project! 
Going to close this as its resolved now.
