### ISSUE TITLE
Safari won't display virtual keyboard on iPad Pro (iOS 13.5.1)

### ISSUE THREAD

**Issue by M0r13n** [jcubic/jquery.terminal#589]
### Issue summary
When using the newest version of iOS and Safari my iPad won't open the virtual keyboard when trying to select the input field. It only works for a very small area on the left of the screen.
This behavior is also present on https://terminal.jcubic.pl/android.html . 

I solved the problem by adding to my CSS file. This also fixes the problem on your Android demo site.

```css
.cmd-clipboard {
    width: 100%!important;
}
```

### Expected behavior
The virtual keyboard opens when I click on the input line.

### Actual behavior
It does not open

### Steps to reproduce
Open https://terminal.jcubic.pl/android.html with an iPad and try to open the virtual keyboard.

### Browser and OS
iOS 13.5.1 + Safari

**Comment by jcubic** [comment]
I made some changes to the way content-editable works on mobile. I think that real problem is that iOS don't use mobile version of the clipboard created using content-editable that allow to use copy/paste on mobile, will test it on browser stack. 

Mobile detection is created using user-agent (I've used regex that I've found somewhere, unfortunately I didn't included credit) I've was reading recently that browser (mostly google) will get rid of user-agent. If it was working on previous iOS/Safari then maybe something changed with user-agent.

I need to investigate. The main issue is that `.cmd-clipboard` is for desktop. Mobile paste was added in 2.15.0 where content editable was added it replaced `.cmd-clipboard` on mobile.

**Comment by jcubic** [comment]
The problem was that iPad iOS 13 removed iPad string from user-agent, here is way to detect new iPad in JavaScript [How to detect iPad and iPad OS version in iOS 13 and Up?](https://stackoverflow.com/a/57924983/387194).

You can test https://terminal.jcubic.pl/android.html the fix will be in next version.

**Comment by M0r13n** [comment]
I just verified it. It works like a charm on my iPad now. 

Good Job!👌🏻
