### ISSUE TITLE
Add nested functions support

### ISSUE THREAD

**Issue by MYDavoodeh** [jcubic/jquery.terminal#594]
Pipes almost work perfectly at this point.
I suppose the only other important feature left to be written is nested functions.
Imagine an special-character='$'
with that in mind a command using the feature will look like this: 
`echo $(echo x)` 
which prints `x`

(Sorry for bad English... but am I making the point here?)

**Comment by jcubic** [comment]
This is something that can be implemented outside of terminal. There are lot of features of bash that you can add. You can try create something like this yourself. It will need to be replacement for pipe, because you can use `echo $(cat hello.txt | less)` I think it will break with current code. 

When I find time maybe I will crate PoC for this.

Can you tell me use case for this, when you're really need this? Or is it just idea. Because right now you can use extended commands that look almost the same. `[[echo x]]` you should even be able to use pipe inside. But for this you always need to use echo because `[[ ]]` need to be passed to echo function in order to execute command. (it was created so server can interact with terminal and send commands)

**Comment by MYDavoodeh** [comment]
Thank you for your answer...

No, honestly there is no actual, particular use case in the back of my mind for this. I just thought it's cool and expected.

Guess I'll have to implement it myself then :)

**Comment by jcubic** [comment]
You can try to create a parser. I was searching recently for bash parser and found two project, but didn't actually check them.

https://github.com/grncdr/js-shell-parse

https://github.com/vorpaljs/bash-parser

Best is way is to just create object with commands and using function as first argument that will give you whole text that user type. If you will make this working you can share this, I will link your project in examples page.

**Comment by jcubic** [comment]
I've build bash-parser for browser, here is CDN link https://cdn.jsdelivr.net/gh/jcubic/static/js/bash-parser.js

The parser create [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) from bash code, that you can evaluate I will check what can I do at Codepen.

**Comment by MYDavoodeh** [comment]
Thanks a lot for your guidance...
This saves me A LOT of time :pray:

**Comment by jcubic** [comment]
I'm closing this issue as out of scope, this is something anyone can implement on top of jQuery Terminal, not need to put this into the library or pipe.js that was created as example but included as extension.
