### ISSUE TITLE
Provide an option to prevent terminal from scrolling to the bottom on click

### ISSUE THREAD

**Issue by ovk** [jcubic/jquery.terminal#596]
Currently the terminal will scroll down to the bottom on click, even though it currently holds focus.

As was discussed in Gitter, having an option that prevents such behaviour would be really nice.

**Comment by jcubic** [comment]
Thanks for adding an issue, I think that it would be better for you case to just don't scroll it terminal is already in focus. But adding option to disable that completely is also nice idea.

**Comment by ovk** [comment]
Is there currently a way to prevent scrolling when terminal is in focus?

**Comment by jcubic** [comment]
No, I need to add this feature.

**Comment by jcubic** [comment]
The jumping was actually never intentional, the code just focus into textarea when you clik anywere on the page, and when terminal was scrolled up it jumped to bottom because textarea was inside command line.

Right now the textarea scroll with the page so focus into textarea never jump to bottom, and there is explicit `scroll_to_bottom()` call in case of clicking on terminal when it's not enabled.
