### ISSUE TITLE
invoke_key usually doesn't do anything?

### ISSUE THREAD

**Issue by hoodmane** [jcubic/jquery.terminal#649]
### Steps
Go to:
https://pyodide-cdn2.iodide.io/dev/full/console.html
type
```javascript
let term = $("body").terminal();
term.invoke_key("CTRL+L");
```
into browser console. 

### Expected behavior
It should the screen.

### Actual behavior
Usually nothing, but once in a while it clears the screen. I haven't come up with any pattern to reproduce the cases where it does work.

### Extra info
You can confirm that the terminal instance is the main one with `term.echo("hi")`. Actually pressing `CTRL+L` clears the screen. The setup code is very simple, all the terminal setup code is ~20 lines of inline script.

**Comment by hoodmane** [comment]
On the other hand, `term.keymap[cmd]()` seems to do what I expected `term.invoke_key(cmd)` to do.

**Comment by jcubic** [comment]
Something probably break this function. Thanks for the report.

**Comment by jcubic** [comment]
Can you tell how do you execute this function. It's working fine, the only case when it's not working is when terminal is disabled is pased or not in focus. Which is almost the same, the terminal is disabled.

**Comment by jcubic** [comment]
If you execute this from dev tools terminal will always be not in focus. So you need `term.focus().invoke_key(cmd)` otherwise it will not work. I can add warning when you try to call invoke_key and the terminal is disabled so it will be obvious what is happening.

The reason why invoke_key don't work when terminal is disabled because it trigger normal Events keydown and keypress that also don't work when terminal is not in focus, it's disabled or paused.

Please check if this works for you, otherwise I will need to investigate little bit more.

**Comment by hoodmane** [comment]
Great, that works, thanks!
