### ISSUE TITLE
Default value for read

### ISSUE THREAD

**Issue by crystalstorm** [jcubic/jquery.terminal#720]
### I have question related to jQuery Terminal

How can one add a default value for `term.read` function which will be directly used when the user hits 'enter'?
Like:
```
term.read('Question: ', 'default answer')
    .then( answer => {
      // answer will be "default answer" if the user hits enter only
    });
```

**Comment by jcubic** [comment]
If user hit enter only answer will be empty string so you can use:
```javascript
term.read('Question: ')
    .then( answer => {
      answer = answer || 'default answer';
      term.echo(answer);
    });
```

This works because in JavaScript empty string is falsy value.

**Comment by crystalstorm** [comment]
@jcubic Thanks, but this will be executed after hitting enter.
Maybe I did not described the issue very well.
I want the "default answer" to be shown in the console as already typed one, only waiting enter to be hit.
In the case above it will be:
```
Question: default answer| 
```
(the last character is a blinking cursor)

**Comment by jcubic** [comment]
Why don't use just use:
```javascript
term.read('Question: default answer');
```
Why you need an API for this?

**Comment by crystalstorm** [comment]
```term.read('Question: default answer');```
will only add to the questioning prompt, and you will not be able to delete "default answer". 
I need a typed answer which the user should be able to delete and write another one if he does not want the default one.

I am using this in a multi-line command, which after answering one question - asks another question until it got 3 answers. I chain term.reads inside the promise resolutions like this:
```
term.read('Question1: ')
    .then( answer1 => {
        term.read('Question2: ').then(answer2 => {
           // etc. put more questions here...
         });
    });
```
And I want to make "saved" answers from previous runs of the command, that's why I need the default answer option.

**Comment by jcubic** [comment]
You can use something like this:

```javascript
function read(prompt, default_answer) {
    var promise = term.read(prompt);
    term.insert(default_answer);
    return promise;
}

read('Question: ', 'default answer').then(answer => {

});
```

And if you will want to force the user to pick the answer and don't delete the command entirely, you will need to use low level push where you will have full control. `read()` is just syntax sugar, helper for simple usage case. You see how it was implemented in the code.

[jquery.terminal-src.js#L10514](https://github.com/jcubic/jquery.terminal/blob/465136e58c561a686f301b0bb33143fbcd8bf519/js/jquery.terminal-src.js#L10514)

If you want something different you can use it's code and modify it to your fit. The implementation handle bit more cases, you can use something simpler.

But way to add method to jQuery Termial object (I need to documented on the wiki) is to add jQuery Plugin like this:

```javascript
$.fn._read = function() {
    var term = this.terminal();
    var promise = term.read(prompt);
    term.insert(default_answer);
    return promise;
};
```

terminal object extend (using `$.extend`) jQuery object, so you can use it to add new methods. Unfortunately you can overwrite read (because read is add to the object itself not to prototype).

**Comment by jcubic** [comment]
One issue with your site, the footer is not visible so the page overfload and you have two scrollbars. You should use:
```css
#term {
    height: calc(100vh - 25px);
}
```
25px is the height of the footer, it should change when footer is updated.

**Comment by crystalstorm** [comment]
@jcubic thanks! :) I applied the css fix.
I could not make this to work though
```
function read(prompt, default_answer) {
    var promise = term.read(prompt);
    term.insert(default_answer);
    return promise;
}
```
But I understood that it's not supported directly and I need to write my own function for this. I will close the ticket.

**Comment by jcubic** [comment]
The main function that is used for `read()` is `push()` that create nested interpreter. And to inject the command you use `insert()`. or `set_command()`
