### ISSUE TITLE
Self XSS

### ISSUE THREAD

**Issue by Nahiiko** [jcubic/jquery.terminal#727]
Self XSS is possible by typing something like "onclick="alert(1);"

I think it's because data-text doesn't contain sanitized characters.
Don't think it's critical but there you go regardless :)

**Comment by jcubic** [comment]
Can you create a PoC for this? Without reproduction it's like saying "your library is broken" without saying anything else.

Please show example, how this lead to XSS, if it's true is more problematic than you think. 
I've already found some XSS long ago and reported it to NPM, because the developer (User) of the library could unintentionally create reflected XSS if he was not careful. That's why I've disabled some options by default.

**Comment by jcubic** [comment]
Ok, I was able to reproduce, I was testing in Terminal that is not affected.

Thanks for the report.

**Comment by jcubic** [comment]
I think that I've forget in one place to escape `"` with `&quot;` it's happen only when formatting is enabled. But outside of formatting the code is not escaped. Probably the code for data-text attribute was added later so data-text is attribute is always present, but escaping was not added.

And just FYI: to prevent the XSS you can use this code:
```javascript
$.terminal.new_formatter([/([\s\S]+)/g, '[[;;]$1]']);
```
that wraps whole text into empty formatting, it's no op but it will trigger the code that do escape the `"` with `&quot;`.
