### ISSUE TITLE
Issue with ANSI Formatting

### ISSUE THREAD

**Issue by QuocTrung76** [jcubic/jquery.terminal#835]
Issue summary:
When text is used ANSI formatting with '[' and ']' surrounding the text, the text is skipped.

jquery terminal format:
term.echo('[\x1b[0;32m  Hello  \x1b[0m] World');

Expected behavior
```[  Hello  ] World```

Actual behavior
The text is skipped
```World```

**Comment by jcubic** [comment]
Interesting bug, thanks for reporting it. Actually, this is already fixed on devel branch. I was working on ANSI formatting recently (as part of paid support) and it seems that it works there.

I'm marking it as resolved and will close when this will be released.

**Comment by jcubic** [comment]
I'm reopening because I needed to remove the code I did for paid work. It's on the experimental [ansi-formatting](https://github.com/jcubic/jquery.terminal/tree/ansi-formatting) branch.
The code after the rewrite of ANSI formatting is x10 slower because it was using a few `$.terminal.substring()` in a loop, the original code is much faster.

**Comment by jcubic** [comment]
The code seems to work:

```javascript
$.terminal.from_ansi('[\x1b[0;32m Hello \x1b[0m] World')
```
returns:
```javascript
'[[[;#008400;] Hello ]] World'
```

But this in turn is extended command, it try to invoke the command: `[;#008400;] Hello` which is correct to prevent this you need to escape brackets

```javascript
term.echo('[\x1b[0;32m Hello \x1b[0m\\] World');
```

I'm closing the issue.
