### ISSUE TITLE
this.echo( div, { typing: true, delay: 100 }) does not work

### ISSUE THREAD

**Issue by philippehenri** [jcubic/jquery.terminal#847]
Hello

I took your example to display html content, and added the "typing" effet which works with pure text but NOT with html

               var div = $('<p>Hello <strong>World</strong></p>')

                this.echo( div, { typing: true, delay: 100 });

this does nothing. Is it normal ?

ps:but    this.echo( div); works

thanks
philippe

**Comment by jcubic** [comment]
This is not a bug you can echo HTML code like this. You need to use raw option and animation doesn't work with animation. There would need to be HTML parser inside jQuery Terminal. Raw option is only when you don't want to use jQuery Terminal features (Formatting syntax), so you disable them completely.

**Comment by jcubic** [comment]
But I should probably give a warning of something and update the documentation that animation is only for strings.

**Comment by philippehenri** [comment]
HI

ok thanks well noted.  I understand it is impossible with complex html but what about a single <div style="xxx">text to animate </div>? that will allow so set at least font-size, background or color, would be nice.

ps: yes maybe a warning would be nice as it took me a while before I found that it was the problem.

**Comment by jcubic** [comment]
No, it will not be good idea because I will need to have full HTML parser after a while.

And you can make font size background and color with jQuery terminal only not with bare HTML.

Example:
```javascript
term.echo('[[;red;]text to animate]');
```
The syntax is not very intuitive but it's meant to be used mostly by machines. You can do everything that HTML has you can add basic style, color, and background. But if you want you can add [HTML attributes as well like `style`](https://github.com/jcubic/jquery.terminal/wiki/Formatting-and-Syntax-Highlighting#attribute-formatter) if you want.

**Comment by jcubic** [comment]
And to make the jQuery Terminal syntax simple to use there is [XML formatting](https://github.com/jcubic/jquery.terminal/wiki/Formatting-and-Syntax-Highlighting#extension-xml-formatter) that allows using HTML-like code inside jQuery Terminal where you don't need to worry about stuff like [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting), because there is only limited number of tags.

**Comment by jcubic** [comment]
There is also a lot of CodePen demos that show how to use the library.

If you think the docs are bad, I know they could be better (Wiki is not ideal) but if you have any suggestions on how to improve docs, I'm all ears.

**Comment by philippehenri** [comment]
thanks. it was just a small defailt. the doc is excellent !! and the codepen examples also ! thanks.
