### ISSUE TITLE
echo() clear screen

### ISSUE THREAD

**Issue by devwoojin** [jcubic/jquery.terminal#862]
**Issue summary**
I used the echo() function to clear the screen, but it doesn't work.
It should be operated with the echo() function.

**Expected behavior**
clear screen

**Actual behavior**
not working

**Steps to reproduce**
$('#divRemoteTerminal').terminal((command) => {}, {
              exit: false,
              name: "remoteconsole",
              height: this.$("WTERMINAL").$height,
              greetings: TerminalGreetings,
              prompt: '> ',
              // automatically scroll to the bottom of the screen when new lines are added
              scrollOnEcho: true,
              outputLimit: 100,
              ansi: true // enable ANSI escape codes
});

test code

this.echo('\x1b[2J'); 
var clearScreenAndMoveCursor = '\x1b[2J\x1b[1;1H';
this.echo(clearScreenAndMoveCursor );

**Comment by jcubic** [comment]
It will not work because ANSI formatting is not absolute like with a normal ASNI terminal. It can only be used to operate over a single echo. This is the limitation of the architecture of the library.

There is a plan to add Canvas Mode #671 that will allow having something like this, but I don't know when something like this will be added and how hard will be to implement.
