### ISSUE TITLE
Correct Display in ReadOnly Mode

### ISSUE THREAD

**Issue by KiddoV** [jcubic/jquery.terminal#884]
I want my terminal to ``readonly`` so I did:
```ts
{
    ...
    onInit(t) {
        t.freeze(true);
    }
}
```
Everything works find, only one thing still bordering me is the space at the end of the terminal. 
Is it should be gone so the terminal would looks better?

![Untitled](https://github.com/jcubic/jquery.terminal/assets/28552977/bd01ed6a-2afa-4121-a527-3f34330ef04f)

**Comment by jcubic** [comment]
I need to check, because read only terminal was supposed to be broken for a long time, there is open issues somewhere. The issue was about virtual keyboard. It was open for years. I'm not able to find it right now when I'm writing this because I'm on mobile app.

**Comment by jcubic** [comment]
this is the issue https://github.com/jcubic/jquery.terminal/issues/449 almost half number.

**Comment by KiddoV** [comment]
Is there any "manual way" to remove that space. Tried change height to 0 and display to none not working.

**Comment by KiddoV** [comment]
No, this is an offline application.

**Comment by KiddoV** [comment]
I will when I have time. Thanks!

**Comment by jcubic** [comment]
Thanks, I will also try to reproduce on my own.

**Comment by jcubic** [comment]
Do you have an empty prompt? I don't see any empty space:

https://codepen.io/jcubic/pen/xxQZaKy

Please if you can, recreate the issue.

**Comment by KiddoV** [comment]
Thanks for taking the time on this:

https://codepen.io/kiddov/pen/VwVaYOa

Set ``prompt: ""`` because it doesn't make sense displaying the ``> `` in read-only mode.

**Comment by jcubic** [comment]
It does make sense to use a prompt if you have a Virtual Keyboard that is used to type the characters into CMD.

But to fix your issue you can use this CSS:

```css
.terminal .cmd {
    height: 0;
    overflow: hidden;
}
```

`display: none;` will not work because it throws an error, probably because the prompt is used to calculate the size of the characters without its width and height being 0 and it ends up in an invalid state.

I can add an API to cmd to hide the whole command, that doesn't break anything:

```javascript
this.freeze(true).cmd().hide();
```
it will overwrite the default jQuery method, I can also add complementary `show()`.

**Comment by KiddoV** [comment]
Thanks, it looks good now!
