### ISSUE TITLE
Type one SPACE but cursor moves two.

### ISSUE THREAD

**Issue by rockcarry** [jcubic/jquery.terminal#886]
### Issue summary
Everything works good, but I found a problem, when input a SPACE, the cursor moves two SPACE. it make the output likes very strange. I tested on Edge, Chrome, get same result. but when copy the text from terminal, and paste to a editor, the SPACE nubmers are correct. That mean the input, and echo text content is good, but the display is incorrect ?

### Expected behavior
I expected displaying like:
```
1 3 5 7
1234567
```

### Actual behavior
```
1  3  5  7
1234567
```

### Steps to reproduce

steps to reproduce:
1. input 1 SPACE 3 SPACE 5 SPACE 7 ENTER
2. input 1234567 ENTER

### Browser and OS
windows 7 and windows 10, Edge and Chrome

**Comment by jcubic** [comment]
I'm not able to reproduce this on BrowserStack can you create a demo where this can be observed? Do you see this on the demo: https://terminal.jcubic.pl/#demo

**Comment by rockcarry** [comment]
![image](https://github.com/jcubic/jquery.terminal/assets/1675029/00e9195a-c28f-4d84-b510-0496b262926a)
yes can reproduce on your demo. see the above picture.
I am using Chinese language, does it related to language of OS or browser ?

**Comment by jcubic** [comment]
It looks like your OS doesn't have a monospace font. This should be installed on every system as it's default font. I would expect that you deleted the font from your system that is not working correctly.

**Comment by jcubic** [comment]
This is how it works in Windows 10 and Edge in the browser stack:

![Windows 10 + Edge and jQuery Terminal website](https://github.com/jcubic/jquery.terminal/assets/280241/cd377a4a-9d5f-4d9c-89b6-a1829c63fbcf)

As you can see the font is monospace not like in your case sans-serif. So the problem is with your system not with the library.

**Comment by rockcarry** [comment]
I tested on two laptop (Win10/Win10) and one desk PC (Win7). all get same test result.
I am checking the monospace font is correctly installed.
I don't intall any extenions or plug-ins in my brower.

**Comment by jcubic** [comment]
Can you open dev tools and see what font you have when you inspec the terminal?

**Comment by rockcarry** [comment]
> This is how it works in Windows 10 and Edge in the browser stack:
> 
> ![Windows 10 + Edge and jQuery Terminal website](https://user-images.githubusercontent.com/280241/250362538-cd377a4a-9d5f-4d9c-89b6-a1829c63fbcf.png)
> 
> As you can see the font is monospace not like in your case sans-serif. So the problem is with your system not with the library.

your test result looks good. so I must install monospace ? or there any other way to config a mono space font, that had been intall in OS ?

**Comment by jcubic** [comment]
Sorry I have no idea, you can ask on [superuser](https://superuser.com/) or on [Reddit](https://www.reddit.com/). I would expect that the font is missing. Did you upgrade Windows recently? it looks like this is something common because there is an article about this on Microsoft website if you google "[monospcae font missing Microsoft edge windows 10](https://www.google.com/search?hl=pl&q=monospcae%20font%20missing%20Microsfot%20edge%20windows%2010)"

**Comment by rockcarry** [comment]
I can open browser's dev tools CSS panel, but where to see it ?

**Comment by rockcarry** [comment]
I found the root cause. the monospace of browser is configureable in browser's Settings. if set wrong font family. the display will be abnormal. I change the setting in browser. It looks good now.
Thank you for your help.
